### ISSUE TITLE
mangocoind sync stuck

### ISSUE THREAD

**Issue by madouz** [mangocoinproject/mangocoin#1]
Hi. I have compiled latest git repo on ubuntu 16.04 and blockchain sync is stuck at block 1932. I have tried resync and also deleting cache files and resync and is stuck each time. I have also tried gui wallet and remote nodes are also not working. How can i fix this?
![mangocoind](https://user-images.githubusercontent.com/24627386/62220508-70d2f400-b3b0-11e9-8df7-ed70f5b9e94c.png)

**Comment by wombatlabs** [comment]
That was fixed in a previous release.

**Comment by knkrth** [comment]
Still facing the same issue. Which commit was the fix?

**Comment by wombatlabs** [comment]
Try deleting blockchain data and resyncing with the chain.
